version: "3.8"

services:
  # ==========================
  # Auth Service (.NET)
  # ==========================
  authservice:
    build:
      context: ./backend/AuthService
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=AuthDB;user=root;password=YourStrong@Password123;
    depends_on:
      - db
    networks:
      - mocha-network

  # ==========================
  # User Service (Spring Boot)
  # ==========================
  userservice:
    build:
      context: ./backend/UserService
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/UserDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=YourStrong@Password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=UserService
    depends_on:
      - db
    networks:
      - mocha-network
 # ==========================
  # Post Service (Spring Boot)
  # ==========================
  postservice:
    build:
      context: ./backend/PostService
      dockerfile: Dockerfile
    container_name: postservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/PostDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=YourStrong@Password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=PostService
    depends_on:
      - db
    networks:
      - mocha-network

  # ==========================
  # API Gateway (Ocelot)
  # ==========================
  apigateway:
    build:
      context: ./backend/ApiGateway
      dockerfile: Dockerfile
    container_name: apigateway-mocha
    ports:
      - "8000:8080"
    depends_on:
      - authservice
      - userservice
    networks:
      - mocha-network

  # ==========================
  # MySQL Database
  # ==========================
  db:
    image: mysql:8.0
    container_name: mocha-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YourStrong@Password123
      MYSQL_DATABASE: AuthDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mocha-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pYourStrong@Password123"]
      interval: 10s
      timeout: 5s
      retries: 10

# ==========================
# Networks & Volumes
# ==========================
networks:
  mocha-network:
    name: mocha-network
    driver: bridge

volumes:
  mysql-data:
